# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mayra\OneDrive\Escritorio\Facu\5to Semestre\Visualizacion\Agregar_usuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mysql
from mysql.connector.errors import Error
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QMessageBox


class Ui_fondo(object):
    lstDatos=[]
    def setupUi(self, fondo):
        fondo.setObjectName("fondo")
        fondo.resize(592, 503)
        fondo.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color:rgb(97, 97, 244);\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(fondo)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 170, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 220, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 320, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.camponombres = QtWidgets.QLineEdit(self.centralwidget)
        self.camponombres.setGeometry(QtCore.QRect(200, 160, 281, 31))
        self.camponombres.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.camponombres.setObjectName("camponombres")
        self.campoapellidos = QtWidgets.QLineEdit(self.centralwidget)
        self.campoapellidos.setGeometry(QtCore.QRect(200, 370, 281, 31))
        self.campoapellidos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.campoapellidos.setObjectName("campoapellidos")
        self.HBO = QtWidgets.QLabel(self.centralwidget)
        self.HBO.setGeometry(QtCore.QRect(90, 0, 311, 91))
        self.HBO.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color:rgb(97, 97, 244);\n"
"")
        self.HBO.setObjectName("HBO")
        self.campopais = QtWidgets.QLineEdit(self.centralwidget)
        self.campopais.setGeometry(QtCore.QRect(200, 260, 281, 31))
        self.campopais.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.campopais.setObjectName("campopais")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(160, 100, 171, 20))
        self.label_8.setObjectName("label_8")
        self.campocorreo = QtWidgets.QLineEdit(self.centralwidget)
        self.campocorreo.setGeometry(QtCore.QRect(200, 210, 281, 31))
        self.campocorreo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.campocorreo.setObjectName("campocorreo")
        self.campopassword = QtWidgets.QLineEdit(self.centralwidget)
        self.campopassword.setGeometry(QtCore.QRect(200, 310, 281, 31))
        self.campopassword.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.campopassword.setObjectName("campopassword")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(130, 260, 31, 31))
        self.label_9.setObjectName("label_9")
        self.Registro_usuario = QtWidgets.QPushButton(self.centralwidget)
        self.Registro_usuario.setGeometry(QtCore.QRect(200, 430, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Registro_usuario.setFont(font)
        self.Registro_usuario.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(111, 118, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(121, 139, 255);\n"
"}")
        self.Registro_usuario.setObjectName("Registro_usuario")
        self.salir_crear_cuenta = QtWidgets.QPushButton(self.centralwidget)
        self.salir_crear_cuenta.setGeometry(QtCore.QRect(400, 430, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.salir_crear_cuenta.setFont(font)
        self.salir_crear_cuenta.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(111, 118, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(121, 139, 255);\n"
"}")
        self.salir_crear_cuenta.setObjectName("salir_crear_cuenta")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 380, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        fondo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(fondo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 592, 21))
        self.menubar.setObjectName("menubar")
        fondo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(fondo)
        self.statusbar.setObjectName("statusbar")
        fondo.setStatusBar(self.statusbar)


        self.salir_crear_cuenta.clicked.connect(self.salir_crear_cuenta_Clicked)
        self.retranslateUi(fondo)
        QtCore.QMetaObject.connectSlotsByName(fondo)
        self.Registro_usuario.clicked.connect(self.Registro_usuario_Clicked)


    def retranslateUi(self, fondo):
        _translate = QtCore.QCoreApplication.translate
        fondo.setWindowTitle(_translate("fondo", "MainWindow"))
        self.label.setText(_translate("fondo", "<html><head/><body><p><span style=\" color:#fcfcfc;\">Nombre:</span></p><p><br/></p></body></html>"))
        self.label_2.setText(_translate("fondo", "<html><head/><body><p><span style=\" color:#ffffff;\">Correo electrónico:</span></p></body></html>"))
        self.label_3.setText(_translate("fondo", "<html><head/><body><p><span style=\" color:#ffffff;\">Contraseña:</span></p></body></html>"))
        self.HBO.setText(_translate("fondo", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600; color:#ffffff;\">HBO</span></p></body></html>"))
        self.label_8.setText(_translate("fondo", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Registro de usuario</span></p></body></html>"))
        self.label_9.setText(_translate("fondo", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">País:</span></p></body></html>"))
        self.Registro_usuario.setText(_translate("fondo", "Registrar"))
        self.salir_crear_cuenta.setText(_translate("fondo", "Salir"))
        self.label_4.setText(_translate("fondo", "<html><head/><body><p><span style=\" color:#ffffff;\">Confirmar contraseña:</span></p></body></html>"))

    def salir_crear_cuenta_Clicked(self):
        fondo.close()


    def Registro_usuario_Clicked(self):
        lstDatos = []  # Asegúrate de que lstDatos contenga datos válidos
        lstDatos.append(self.camponombres.text())
        lstDatos.append(self.campocorreo.text())
        lstDatos.append(self.campopais.text())
        lstDatos.append(self.campopassword.text())
        Msg = QMessageBox()
        Msg.setWindowTitle("Informacion")
        Msg.setText("Usuario Agregado Correctamente")
        Msg.setIcon(QMessageBox.Information)
        Msg.setStandardButtons(QMessageBox.Ok)
        Msg.exec_()
        

        if lstDatos:
                id_Usuario = 0  # Accede al primer elemento de lstDatos
                nombre = lstDatos[0]
                correo_electronico = lstDatos[1]
                país = lstDatos[2]
                contrasena = lstDatos[3]   # Puedes asignar un valor por defecto si es necesario
        else:
                id_Usuario = "Sin nombre"
                nombre = "Sin nombre"
                correo_electronico = "Sin correo"
                país = "Sin país"
                contrasena = "Sin contra"


    # Luego llama a la función ConexionDB pasando id_Usuario como argumento
        self.ConexionDB(id_Usuario, nombre, correo_electronico, país, contrasena)

    def ConexionDB(self, id_Usuario, nombre, correo_electronico, país, contrasena):
        print("La función ConexionDB se ha llamado")
        try:
                db_connection = mysql.connect(user="root", password="Pedraza26", host="localhost", database="mydb")
                db_cursor = db_connection.cursor()
                
                insert_query = "INSERT INTO registro_usuario (id_Usuario, nombre, correo_electronico, país, contrasena) VALUES (%s, %s, %s, %s, %s)"
                values = (id_Usuario, nombre, correo_electronico, país, contrasena)
                
                db_cursor.execute(insert_query, values)
                db_connection.commit()
        except mysql.Error as e:
                print(e.msg)
        finally:
                db_cursor.close()
                db_connection.close()
                

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fondo = QtWidgets.QMainWindow()
    ui = Ui_fondo()
    ui.setupUi(fondo)
    fondo.show()
    sys.exit(app.exec_())
