# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mayra\OneDrive\Escritorio\Facu\5to Semestre\Visualizacion\inicio_sesion.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import mysql.connector as mysql
from mysql.connector.errors import Error
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from catalogo import Ui_catalogo
from Agregar_usuario import Ui_fondo

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 581)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(-150, -10, 961, 611))
        self.groupBox.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color:rgb(97, 97, 244);\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(330, 320, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.campopassword = QtWidgets.QLineEdit(self.groupBox)
        self.campopassword.setGeometry(QtCore.QRect(330, 350, 231, 31))
        self.campopassword.setStyleSheet("border-radius:5px;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.campopassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.campopassword.setObjectName("campopassword")
        self.campousername = QtWidgets.QLineEdit(self.groupBox)
        self.campousername.setGeometry(QtCore.QRect(330, 270, 231, 31))
        self.campousername.setStyleSheet("border-radius:5px;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.campousername.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.campousername.setObjectName("campousername")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(330, 240, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.login = QtWidgets.QPushButton(self.groupBox)
        self.login.setGeometry(QtCore.QRect(330, 430, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.login.setFont(font)
        self.login.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(111, 118, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(121, 139, 255);\n"
"}")
        self.login.setObjectName("login")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(360, 160, 161, 71))
        self.label_4.setStyleSheet("font: italic 20pt \"Gill Sans MT\";\n"
"color:rgb(255, 255, 255);\n"
"")
        self.label_4.setObjectName("label_4")
        self.error = QtWidgets.QLabel(self.groupBox)
        self.error.setGeometry(QtCore.QRect(150, 380, 211, 16))
        self.error.setStyleSheet("font: 10pt \"Gill Sans MT\";color:red;")
        self.error.setText("")
        self.error.setObjectName("error")
        self.HBO = QtWidgets.QLabel(self.groupBox)
        self.HBO.setGeometry(QtCore.QRect(280, 20, 311, 131))
        self.HBO.setObjectName("HBO")
        self.login_2 = QtWidgets.QPushButton(self.groupBox)
        self.login_2.setGeometry(QtCore.QRect(330, 500, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.login_2.setFont(font)
        self.login_2.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(111, 118, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(121, 139, 255);\n"
"}")
        self.login_2.setObjectName("login_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(390, 470, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_2.raise_()
        self.campopassword.raise_()
        self.campousername.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.error.raise_()
        self.HBO.raise_()
        self.login.raise_()
        self.login_2.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 534, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.login.clicked.connect(self.login_clicked)
        self.login_2.clicked.connect(self.login_2_clicked)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Contraseña:"))
        self.label.setText(_translate("MainWindow", "Usuario:"))
        self.login.setText(_translate("MainWindow", "Iniciar Sesión"))
        self.label_4.setText(_translate("MainWindow", "INICIO SESIÓN"))
        self.HBO.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><a href=\"https://www.hbomax.com/mx/es\"><span style=\" font-size:48pt; font-weight:600; color:#ffffff;\">HBO</span></a></p><p align=\"center\"><a href=\"https://www.hbomax.com/mx/es\"><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">MAX</span></a></p></body></html>"))
        self.login_2.setText(_translate("MainWindow", "Registrate"))
        self.label_3.setText(_translate("MainWindow", "No tienes cuenta?"))

    def ConexionDB(self, P_Usuario, P_Contra):
        print("La función conexionbd se ha llamado")
        lstResul = []
        try:
                tplParametros = (P_Usuario, P_Contra)
                dbConn = mysql.connect(user="root", password="Pedraza26", host="localhost", database="mydb")
                dbCommand = dbConn.cursor()

                dbCommand.callproc("spConsulUsuario",tplParametros)

                for SqlResult in dbCommand.stored_results():
                        lstResul.append(SqlResult.fetchone())

                return lstResul[0]
        except mysql.Error as e:
                print(e.msg)
        finally:
                dbCommand.close()
                dbConn.close()

    def login_clicked(self):
        print("La función login_clicked se ha llamado")
        self.lstValores = self.ConexionDB(self.campousername.text(), self.campopassword.text())
        print("lstValores:", self.lstValores)
        if (self.lstValores is not None):
                self.window = QtWidgets.QMainWindow()
                self.ui = Ui_catalogo()
                self.ui.setupUi(self.window)
                self.ui.set_values(self.lstValores[0], self.lstValores[1])
                MainWindow.hide()
                self.window.show()
        else:
                Msg = QMessageBox()
                Msg.setWindowTitle("Informacion")
                Msg.setText("Revise que el usuario y contraseña este bien escrito")
                Msg.setIcon(QMessageBox.Information)
                Msg.setStandardButtons(QMessageBox.Ok)
                Msg.exec_()
        
    def login_2_clicked(self):
        print("La función login_clicked se ha llamado")
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_fondo()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
