-- MySQL Script generated by MySQL Workbench
-- Thu Nov  9 01:32:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Registro_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Registro_usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Registro_usuario` (
  `id_Usuario` INT NOT NULL,
  `nombre` VARCHAR(250) NULL,
  `correo_electronico` VARCHAR(100) NULL,
  `país` VARCHAR(50) NULL,
  `contrasena` VARCHAR(20) NULL,
  PRIMARY KEY (`id_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Genero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Genero` (
  `id_Genero` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pelicula` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pelicula` (
  `id_Pelicula` INT NOT NULL,
  `Genero_id_Genero` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Pelicula`, `Genero_id_Genero`),
  CONSTRAINT `fk_Pelicula_Genero1`
    FOREIGN KEY (`Genero_id_Genero`)
    REFERENCES `mydb`.`Genero` (`id_Genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pelicula_Genero1_idx` ON `mydb`.`Pelicula` (`Genero_id_Genero` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Reseña`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reseña` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reseña` (
  `id_Reseña` INT NOT NULL,
  `Usuario_id_Usuario` INT NOT NULL,
  `nombre_pelicula` VARCHAR(45) NOT NULL,
  `calificacion` INT NULL,
  `comentario` VARCHAR(500) NULL,
  `Pelicula_id_Pelicula` INT NOT NULL,
  `Pelicula_Genero_id_Genero` INT NOT NULL,
  PRIMARY KEY (`id_Reseña`, `Usuario_id_Usuario`, `nombre_pelicula`, `Pelicula_id_Pelicula`, `Pelicula_Genero_id_Genero`),
  CONSTRAINT `fk_Reseña_Usuario`
    FOREIGN KEY (`Usuario_id_Usuario`)
    REFERENCES `mydb`.`Registro_usuario` (`id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reseña_Pelicula1`
    FOREIGN KEY (`Pelicula_id_Pelicula` , `Pelicula_Genero_id_Genero`)
    REFERENCES `mydb`.`Pelicula` (`id_Pelicula` , `Genero_id_Genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Reseña_Usuario_idx` ON `mydb`.`Reseña` (`Usuario_id_Usuario` ASC) VISIBLE;

CREATE INDEX `fk_Reseña_Pelicula1_idx` ON `mydb`.`Reseña` (`Pelicula_id_Pelicula` ASC, `Pelicula_Genero_id_Genero` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
